name: Gitlab Provisioner Config

on:
  push:
    branches:
      - dev
      - master

jobs:
  test:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: validate
          tf_actions_working_dir: .
