name: Terraform Validator

on:
  push:
    branches:
      - dev
      - master
      - testing

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: validate
          tf_actions_working_dir: .
